### PR TITLE
feat: nebulagraph as database integration

### PR DESCRIPTION
**Pull request by wey-gu**
- This is the Phase 0 implementation, where the search part is not natively database-side.
- Also, some chore work was done

### CODE REVIEW

**Comment by wey-gu** [comment]
As we discussed offline, I was unable to verify it (due to not having an OAI API key) end-to-end. However, some other changes should be merged first. Also, please note that NebulaGraph integration is still a work in progress and is mentioned as such in the readme file.

**Comment by yoheinakajima** [comment]
On glance looks good, but does adding entity type in the search break anything? Where we begging the entity type? My guys says searching through all entities (not just entity type) makes sense...

**Comment by wey-gu** [comment]
> On glance looks good, but does adding entity type in the search break anything? Where we begging the entity type? My guys says searching through all entities (not just entity type) makes sense...

Was initially adding entity type to search due to [one of the API call was like that](https://github.com/yoheinakajima/mindgraph/blob/36e7fceba7b18315056e23f1deb20223ca197173/app/views.py#L155), it turned out that both are needed(in AI Search, it required the one w/o entity_type), thus I introduced both ones.

Now it's verified working.

https://github.com/yoheinakajima/mindgraph/assets/1651790/fef770af-df50-4b99-a814-e19c76e47eef

**Comment by yoheinakajima** [comment]
Thank you!

**Pull request merged**
